// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT6sdu8O9kFt41sAIpMPw-C3-Fi6Wz5xc',
    appId: '1:1056330439464:web:e9deeb4b6a21cff5e50e1d',
    messagingSenderId: '1056330439464',
    projectId: 'simple-flutter-4665c',
    authDomain: 'simple-flutter-4665c.firebaseapp.com',
    storageBucket: 'simple-flutter-4665c.appspot.com',
    measurementId: 'G-77CWBZ0EMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaUCFRsSXkiPYXuJzKZ7C_fNvrdkBQFM',
    appId: '1:1056330439464:android:5d58e88386cce334e50e1d',
    messagingSenderId: '1056330439464',
    projectId: 'simple-flutter-4665c',
    storageBucket: 'simple-flutter-4665c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQwxQhSxMfFaJQl37BohRLF2xhjDhhM4',
    appId: '1:1056330439464:ios:f74da01ba2ca394fe50e1d',
    messagingSenderId: '1056330439464',
    projectId: 'simple-flutter-4665c',
    storageBucket: 'simple-flutter-4665c.appspot.com',
    iosClientId: '1056330439464-fif999q4io7pe0tm8fh2dvsfpjmsd50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQwxQhSxMfFaJQl37BohRLF2xhjDhhM4',
    appId: '1:1056330439464:ios:e11f279550dc4dd0e50e1d',
    messagingSenderId: '1056330439464',
    projectId: 'simple-flutter-4665c',
    storageBucket: 'simple-flutter-4665c.appspot.com',
    iosClientId: '1056330439464-n4cfvl3bjtin6f62eoq4n4vr27dr16t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFlutter.RunnerTests',
  );
}
